spring:

  application:
    name: xml-processing-engine

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=xml_processing_engine;encrypt=true;trustServerCertificate=true
    username: root
    password: Asdfg!@1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:

  level:
    org.flywaydb: INFO

processor:
  instance:
    name: ${HOSTNAME:INSTANCE-1}